#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON_OK                             106
#define IDI_ICON_FAILE                          108
#define IDI_ICON_RUN                            110
#define IDI_ICON_EMPTY                          112
#define IDD_DIALOG_TEST                         115
#define IDD_SETTING                             116
#define IDD_RUN                                 117
#define DLG_MAIN                                118
#define IDC_STATIC_RS1                          1000
#define IDC_STATIC_STATE                        1000
#define IDC_COMBO_PORT                          1001
#define IDC_STATIC_INPUT3                       1001
#define IDC_TAB_MAIN                            1001
#define IDC_BUTTON_START                        1002
#define IDC_STATIC_RS2                          1002
#define IDC_STATIC_CONSOLE                      1003
#define MP_PATH                                 1003
#define IDC_BUTTON_RS232_SCAN                   1004
#define IDC_EDIT_CONSOLE                        1005
#define IDC_STATIC_INPUT                        1006
#define USER_NAME                               1006
#define IDC_LIST_REPORT                         1007
#define IDC_EDIT_INPUT                          1008
#define PASSWORD                                1008
#define IDC_EDIT_NO                             1009
#define IDC_BUTTON_YES_NO_OK                    1010
#define IDC_STATIC_RS232                        1012
#define IDC_STATIC_TIMER                        1013
#define IDC_STATIC_INPUT1                       1014
#define IDC_EDIT_INPUT1                         1015
#define IDC_STATIC_INPUT2                       1016
#define IDC_EDIT_INPUT2                         1017
#define IDC_BUTTON_RESTART                      1019
#define IDS_STRING_START                        40000
#define IDS_STRING_STOP                         40001
#define IDS_STRING_REPORT_ITEM                  40002
#define IDS_STRING_REPORT                       40003
#define IDS_STRING_REPORT_TIME                  40004
#define IDC_BUTTON_YES_NO_FAIL                  40005
