#!/bin/sh

eth=eth0 
ftpserver=$1
ftpid=$2
ftppw=$3

#ftpserver=192.168.11.2
#ftpid=ftp_tester
#ftppw=adlink
text=none

echo "Start PCBA_Function_Test = $eth "

if [ $(ifconfig | grep $eth | wc -l) = 0 ]; then
	ifconfig $eth up 
	sleep 18 
fi

ip=$(ifconfig $eth 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')
# echo "ip=$ip"

if [ -f ./download_net ]; then
        rm ./download_net
        sync
fi

udhcpc -i $eth & 
#dhclient $eth & 
sleep 10

if [ "$(ifconfig $eth | awk 'sub(/inet addr:/,""){print $1}' | wc -l)" -eq "0" ]; then
	pid=$(ps ax | grep "udhcpc -i $eth" | grep -v grep | awk '{print $1}')
#	echo "pid=$pid" 
	kill $pid
	echo "ETH $eth   : no link"
	exit 0
fi

if [ "$(ping -I $eth -c 3 $ftpserver | grep $ftpserver | wc -l)" -gt "2" ];then
	ftpget -u $ftpid -p $ftppw $ftpserver download_net TEST_ETHERNET 
	text=$(cat ./download_net)
else
	text=none	
fi

if [ -f ./download_net ]; then
	rm ./download_net
	sync
	if [ $text = ftp_pass ]; then
		echo "ETH $eth   : PASS"
	else
		echo "ETH $eth   : FAIL"
	fi
else
	echo "ETH $eth   : FAIL"
fi



